example:
  property: "bannsi piece service config"

jwt:
  secret: "{cipher}426217b5624ea34eb0c621761df3f1c20f4fa668189597c9d08fd78ef1cf02a1"
  
spring:
  jpa:
    database: "MYSQL"
    show-sql: "false"
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        ddl-auto: "update"
  datasource:
    platform:  "mysql"
    url: jdbc:mysql://jinho-db.crrywx8kuivs.ap-northeast-2.rds.amazonaws.com:3306/bansi
    username: "admin"
    password: "{cipher}440d48521438bca4ff630208c707d79d08791de4e00713bd6d5ae320591024f5"
    testWhileIdle: "true"
    validationQuery: "SELECT 1"
  database:
    driverClassName: "org.mysql.Driver"
  profiles:
    include:
      - aws
      - credentials
  servlet:
    multipart:
      max-file-size: 50MB
      max-request-size: 50MB

# cloud:
#     aws:
#         s3:
#             bucket: jinho
#         region:
#             static: ap-northeast-2
#         stack:
#             auto: false
#         credentials:
#             instanceProfile: true
#             accessKey: "{cipher}49fa3542b2c0fdf9aed98fd00f8facff74f70001ac5f00314df851fe519cbe8112e50030cb978b99f6cdff25745e05d3"
#             secretKey: "{cipher}d71dad30007945b43ed1548eb1f855a14828af125e231ad2582c2f20490e80a98acf8124f4a9baf1715f7a924957a4bf3717e08cbcce260fc2ea7c289ccc6634"

redis:
  server: "redis"
  port: "6379"

signing:
  key: "345345fsdfsf5345"

logging:
  level:
    org:
      hibernate: ERROR
      springframework:
        web: DEBUG