example:
  property: "bannsi peice service config"

server:
  port: 8081

spring:
  jpa:
    database: "MYSQL"
    show-sql: "false"
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        ddl-auto: "update"
  datasource:
    platform:  "mysql"
    url: jdbc:mysql://db-warm-micro.c8bsxpdjb1j7.ap-northeast-2.rds.amazonaws.com:3306/bannsi
    username: "admin"
    password: "{cipher}35734364183345d9a9a4238302fd099caa3151bd0ee59fb5d445c2e183ed0c29"
    testWhileIdle: "true"
    validationQuery: "SELECT 1"
  database:
    driverClassName: "org.mysql.Driver"
  profiles:
    include:
      - aws
      - credentials
  servlet:
    multipart:
      max-file-size: 50MB
      max-request-size: 50MB

# cloud:
#     aws:
#         s3:
#             bucket: jinho
#         region:
#             static: ap-northeast-2
#         stack:
#             auto: false
#         credentials:
#             instanceProfile: true
#             accessKey: "{cipher}49fa3542b2c0fdf9aed98fd00f8facff74f70001ac5f00314df851fe519cbe8112e50030cb978b99f6cdff25745e05d3"
#             secretKey: "{cipher}d71dad30007945b43ed1548eb1f855a14828af125e231ad2582c2f20490e80a98acf8124f4a9baf1715f7a924957a4bf3717e08cbcce260fc2ea7c289ccc6634"

redis:
  server: "redis"
  port: "6379"

signing:
  key: "345345fsdfsf5345"

logging:
  level:
    org:
      hibernate: ERROR
      springframework:
        web: DEBUG