eureka:
    instance:
        preferIpAddress: true
    client:
        registerWithEureka: true
        fetchRegistry: true
        serviceUrl:
            # defaultZone: http://localhost:8761/eureka/
            defaultZone: http://3.36.116.95:8761/eureka/
            
management:
    endpoints:
        web:
            exposure:
                include: 
                    - "*"
    endpoint:
        health:
            show-details: always
            diskspace:
                enabled: true
        env:
            show-details: always
            enabled: true
        endpoint:
            gateway:
                enabled: true
spring:
  cloud:
    gateway:
      globalcors:
        add-to-simple-url-handler-mapping: true
        corsConfigurations:
          '[/**]':
            allowedOrigins: "*"
            allowedMethods: "*"
            allowedHeaders: "*"
            
# server:
#     port: 5555

# spring:
#     main:
#         web-application-type: reactive
#     application:
#         name: gatewayservice
#     profiles:
#         active:
#             default
#     cloud:
#         config:
#             enabled: true
#         gateway:
#             routes:
#                 - id: peiceservice
#                   uri: lb://PEICESERVICE
#                   predicates:
#                     - Path=/peices/**
#                 - id: accoutservice
#                   uri: lb://ACCOUNTSERVICE
#                   predicates:
#                     - Path=/accounts/**
                    