eureka:
    instance:
        preferIpAddress: true
    client:
        registerWithEureka: true
        fetchRegistry: true
        serviceUrl:
            defaultZone: http://localhost:8761/eureka/
            # defaultZone: http://13.209.41.14:8761/eureka/
            
management:
    endpoints:
        web:
            exposure:
                include: 
                    - "*"
    endpoint:
        health:
            show-details: always
            diskspace:
                enabled: true
        env:
            show-details: always
            enabled: true
        endpoint:
            gateway:
                enabled: true
spring:
    cloud:
        config:
            # uri: http://13.125.210.37:8888
            uri: lb://CONFIGSERVER
        gateway:
            globalcors:
                add-to-simple-url-handler-mapping: true
                corsConfigurations:
                    '[/**]':
                        allowedOrigins: "*"
                        allowedMethods: "*"
                        allowedHeaders: "*"

springdoc:
    paths-to-match:
    - /accounts/**