eureka:
    instance:
        preferIpAddress: true
        # ipAddress: 52.79.130.111
    client:
        registerWithEureka: true
        fetchRegistry: true
        serviceUrl:
            defaultZone: http://3.36.116.95:8761/eureka/

management:
    endpoint:
        health:
            show-details: always
            diskspace:
                enabled: true
        env:
            show-details: always
            enabled: true