server:
  port: 50053

eureka:
    instance:
        preferIpAddress: true
        # ipAddress: 54.180.26.23
    client:
        registerWithEureka: true
        fetchRegistry: true
        serviceUrl:
            # defaultZone: http://13.209.41.14:8761/eureka/
            defaultZone: http://localhost:8761/eureka/

management:
    endpoint:
        health:
            show-details: always
            diskspace:
                enabled: true
        env:
            show-details: always
            enabled: true

springdoc:
    api-docs:
        path: /collections/v3/api-docs