server:
  port: 50052

eureka:
    instance:
        preferIpAddress: true
        ipAddress: 13.209.67.4
    client:
        registerWithEureka: true
        fetchRegistry: true
        serviceUrl:
            defaultZone: http://3.35.52.140:8761/eureka/
            # defaultZone: http://localhost:8761/eureka/

management:
    endpoint:
        health:
            show-details: always
            diskspace:
                enabled: true
        env:
            show-details: always
            enabled: true

springdoc:
    api-docs:
        path: /pieces/v3/api-docs