eureka:
    instance:
        preferIpAddress: true
        ipAddress: 54.180.112.251
    client:
        registerWithEureka: true
        fetchRegistry: true
        serviceUrl:
            defaultZone: http://13.209.41.14:8761/eureka/

management:
    endpoint:
        health:
            show-details: always
            diskspace:
                enabled: true
        env:
            show-details: always
            enabled: true