server:
    port: 5555

spring:
    main:
        web-application-type: reactive
    cloud:
        gateway:
            discovery:
                locator:
                    enabled: true
            routes:
                - id: peiceservice
                  uri: lb://PEICESERVICE
                  predicates:
                    - Path=/peices/**
                - id: accoutservice
                  uri: lb://ACCOUNTSERVICE
                  predicates:
                    - Path=/accounts/**
                    