server:
    port: 8080

spring:
    main:
        web-application-type: reactive
    cloud:
        gateway:
            discovery:
                locator:
                    enabled: true
            routes:
                - id: pieceservice
                  uri: lb://PIECESERVICE
                  predicates:
                    - Path=/pieces/**
                - id: accountservice
                  uri: lb://ACCOUNTSERVICE
                  predicates:
                    - Path=/accounts/**
                - id: collectionservice
                  uri: lb://COLLECTIONSERVICE
                  predicates:
                    - Path=/collections/**