server:
    port: 5555

spring:
    main:
        web-application-type: reactive
    cloud:
        gateway:
          globalcors:
            corsConfigurations:
              '[/**]':
                allowedOrigins: "*"
                allowedHeaders:
                  - x-requested-with
                  - authorization
                  - content-type
                  - credential
                  - X-AUTH-TOKEN
                  - X-CSRF-TOKEN
                allowedMethods:
                  - POST
                  - GET
                  - PUT
                  - OPTIONS
                  - DELETE
            discovery:
                locator:
                    enabled: true
            routes:
                - id: peiceservice
                  uri: lb://PEICESERVICE
                  predicates:
                    - Path=/peices/**
                - id: accountservice
                  uri: lb://ACCOUNTSERVICE
                  predicates:
                    - Path=/accounts/**
                - id: collectionservice
                  uri: lb://COLLECTIONSERVICE
                  predicates:
                    - Path=/collections/**
