example:
  property: "bannsi collection service config"
  
jwt:
  secret: "{cipher}426217b5624ea34eb0c621761df3f1c20f4fa668189597c9d08fd78ef1cf02a1"

spring:
  jpa:
    database: "MYSQL"
    show-sql: "false"
    hibernate:
      ddl-auto: "update"
    properties:
      hibernate:
        ddl-auto: "update"
  datasource:
    platform:  "mysql"
    url: jdbc:mysql://db-warm-micro.c8bsxpdjb1j7.ap-northeast-2.rds.amazonaws.com:3306/bannsi
    username: "admin"
    password: "{cipher}35734364183345d9a9a4238302fd099caa3151bd0ee59fb5d445c2e183ed0c29"
    testWhileIdle: "true"
    validationQuery: "SELECT 1"
  database:
    driverClassName: "org.mysql.Driver"

redis:
  server: "redis"
  port: "6379"

signing:
  key: "345345fsdfsf5345"

logging:
  level:
    org:
      hibernate: ERROR
      springframework:
        web: DEBUG