example:
  property: "bannsi account service config"
  
jwt:
  secret: "{cipher}426217b5624ea34eb0c621761df3f1c20f4fa668189597c9d08fd78ef1cf02a1"

spring:
  jpa:
    database: "MYSQL"
    show-sql: "false"
    hibernate:
      ddl-auto: "update"
    properties:
      hibernate:
        ddl-auto: "update"
  datasource:
    platform:  "mysql"
    url: jdbc:mysql://jinho-db.crrywx8kuivs.ap-northeast-2.rds.amazonaws.com:3306/bansi
    username: "admin"
    password: "{cipher}440d48521438bca4ff630208c707d79d08791de4e00713bd6d5ae320591024f5"
    testWhileIdle: "true"
    validationQuery: "SELECT 1"
  database:
    driverClassName: "org.mysql.Driver"

signing:
  key: "345345fsdfsf5345"

logging:
  level:
    org:
      hibernate: ERROR
      springframework:
        web: DEBUG