server:
    port: 50051
    
eureka:
    instance:
        preferIpAddress: true
        ipAddress: 54.180.109.22
    client:
        registerWithEureka: true
        fetchRegistry: true
        serviceUrl:
            # defaultZone: http://localhost:8761/eureka/
            defaultZone: http://3.35.52.140:8761/eureka/

management:
    endpoint:
        health:
            show-details: always
            diskspace:
                enabled: true
        env:
            show-details: always
            enabled: true

springdoc:
    api-docs:
        path: /accounts/v3/api-docs
        