eureka:
    instance:
        preferIpAddress: true
    client:
        registerWithEureka: true
        fetchRegistry: true
        serviceUrl:
            # defaultZone: http://localhost:8761/eureka/
            defaultZone: http://3.35.50.79:8761/eureka/
management:
    endpoint:
        health:
            show-details: always
            diskspace:
                enabled: true
        env:
            show-details: always
            enabled: true
