server:
    port: 8888
    
spring:
    application:
        name: configserver
    cloud:
        config:
            server:
                git:
                    default-label: main
                    uri: https://github.com/bannsi/bannsi-server
                    searchPaths: config/accountservice, config/pieceservice, config/gatewayservice, config/collectionservice
                encrypt.enabled: false
eureka:
    instance:
        preferIpAddress: true
    client:
        registerWithEureka: true
        fetchRegistry: true
        serviceUrl:
            # defaultZone: http://localhost:8761/eureka/
            defaultZone: http://13.209.41.14:8761/eureka/